spring.application.name=homebuying-assistant



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/homebuying
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.cloud.vertexai.api-key=a9ed7c2fc869a511f5dbf7cbb37fdacb0deee020
spring.cloud.vertexai.model=gemini-1.5

